CREATE TABLE "GCG_4671_LaborStps"(
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQUENCE" CHAR(6),
 "DATE_TIME" DATETIME,
 "LW_SCRAP" NUMERIC(8,2),
 "LW_WOSCRAP" NUMERIC(8,2),
 "STARTUP_SCRAP" NUMERIC(8,2),
 "TOTAL_SCRAP" NUMERIC(8,2));
